# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc83dfe2899c482208ed6083c0bd6b66f9f7a24452dded59f80f30e222df1357f706190a539e3ce9239d3cc6e998e22734922cefd3048be765d923a32de47c0

test:
  secret_key_base: 433ed9f699bb6ae7d82b55b1da5d8de4addad5139c9de500a1d6e0381d3307c366f898e2182be6498ea5454d2f83eaa27a94d7dcf4c98a25c6bae5246faf9274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
